//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "38797303bfffe889")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Common</summary>
	[PublishedContentModel("common")]
	public partial class Common : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "common";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Common(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Common, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Email Template</summary>
	[PublishedContentModel("emailTemplate")]
	public partial class EmailTemplate : Common
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "emailTemplate";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public EmailTemplate(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EmailTemplate, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Admin Email(s): Admin email addresses where information will be sent. Note: Comma separate for multiple emails. Leave blank if email to admin is not needed.
		///</summary>
		[ImplementPropertyType("adminEmail")]
		public string AdminEmail
		{
			get { return this.GetPropertyValue<string>("adminEmail"); }
		}

		///<summary>
		/// Admin Email Body: Email Template
		///</summary>
		[ImplementPropertyType("adminEmailBody")]
		public string AdminEmailBody
		{
			get { return this.GetPropertyValue<string>("adminEmailBody"); }
		}

		///<summary>
		/// Admin From Email
		///</summary>
		[ImplementPropertyType("adminFromEmail")]
		public string AdminFromEmail
		{
			get { return this.GetPropertyValue<string>("adminFromEmail"); }
		}

		///<summary>
		/// Admin Subject: Subject of the email
		///</summary>
		[ImplementPropertyType("adminSubject")]
		public string AdminSubject
		{
			get { return this.GetPropertyValue<string>("adminSubject"); }
		}

		///<summary>
		/// Email User
		///</summary>
		[ImplementPropertyType("emailUser")]
		public string EmailUser
		{
			get { return this.GetPropertyValue<string>("emailUser"); }
		}

		///<summary>
		/// User From Email
		///</summary>
		[ImplementPropertyType("userFromEmail")]
		public string UserFromEmail
		{
			get { return this.GetPropertyValue<string>("userFromEmail"); }
		}
	}

	/// <summary>Containers</summary>
	[PublishedContentModel("containers")]
	public partial class Containers : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containers";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Containers(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Containers, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Common Container</summary>
	[PublishedContentModel("commonContainer")]
	public partial class CommonContainer : Containers
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "commonContainer";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CommonContainer(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CommonContainer, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// List View
		///</summary>
		[ImplementPropertyType("listView")]
		public object ListView
		{
			get { return this.GetPropertyValue("listView"); }
		}
	}

	/// <summary>Email Container</summary>
	[PublishedContentModel("emailContainer")]
	public partial class EmailContainer : Containers
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "emailContainer";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public EmailContainer(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EmailContainer, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// List View
		///</summary>
		[ImplementPropertyType("listView")]
		public object ListView
		{
			get { return this.GetPropertyValue("listView"); }
		}
	}

	/// <summary>Pages</summary>
	[PublishedContentModel("metadata")]
	public partial class Metadata : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "metadata";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Metadata(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Metadata, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// General Settings
		///</summary>
		[ImplementPropertyType("generalSettings")]
		public string GeneralSettings
		{
			get { return this.GetPropertyValue<string>("generalSettings"); }
		}

		///<summary>
		/// seo
		///</summary>
		[ImplementPropertyType("seo")]
		public string Seo
		{
			get { return this.GetPropertyValue<string>("seo"); }
		}

		///<summary>
		/// Settings
		///</summary>
		[ImplementPropertyType("settings")]
		public string Settings
		{
			get { return this.GetPropertyValue<string>("settings"); }
		}

		///<summary>
		/// Url Alias
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return this.GetPropertyValue<string>("umbracoUrlAlias"); }
		}
	}

	/// <summary>Nested Content</summary>
	[PublishedContentModel("nestedContent")]
	public partial class NestedContent : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "nestedContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NestedContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NestedContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>SEO</summary>
	[PublishedContentModel("sEO")]
	public partial class SEO : NestedContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sEO";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SEO(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SEO, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// OG:Description: Open Graph meta tag description, used by Facebook
		///</summary>
		[ImplementPropertyType("oGDescription")]
		public string OGdescription
		{
			get { return this.GetPropertyValue<string>("oGDescription"); }
		}

		///<summary>
		/// Body Scripts: Enter your additional scripts here to be placed in the body. (e.g. Google Analytics, GTM, etc.. )
		///</summary>
		[ImplementPropertyType("sysBodyScripts")]
		public string SysBodyScripts
		{
			get { return this.GetPropertyValue<string>("sysBodyScripts"); }
		}

		///<summary>
		/// sysCanonical Tag: These links are used to identify alternate (canonical) URL’s within the web site.
		///</summary>
		[ImplementPropertyType("sysCanonicalTag")]
		public IEnumerable<IPublishedContent> SysCanonicalTag
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("sysCanonicalTag"); }
		}

		///<summary>
		/// Page Description
		///</summary>
		[ImplementPropertyType("sysDescription")]
		public string SysDescription
		{
			get { return this.GetPropertyValue<string>("sysDescription"); }
		}

		///<summary>
		/// Footer Scripts
		///</summary>
		[ImplementPropertyType("sysFooterScripts")]
		public string SysFooterScripts
		{
			get { return this.GetPropertyValue<string>("sysFooterScripts"); }
		}

		///<summary>
		/// Header Scripts: Enter your additional scripts here to be placed in the head. (e.g. Google Analytics, GTM, etc.. )
		///</summary>
		[ImplementPropertyType("sysHeaderScripts")]
		public string SysHeaderScripts
		{
			get { return this.GetPropertyValue<string>("sysHeaderScripts"); }
		}

		///<summary>
		/// sysKeyword: Enter your SEO tags. Please provide tags in comma(,)
		///</summary>
		[ImplementPropertyType("sysKeyword")]
		public string SysKeyword
		{
			get { return this.GetPropertyValue<string>("sysKeyword"); }
		}

		///<summary>
		/// OG:Image
		///</summary>
		[ImplementPropertyType("sysOgImage")]
		public IPublishedContent SysOgImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("sysOgImage"); }
		}

		///<summary>
		/// OG:Title: Open Graph meta tag title, used by Facebook and Google.
		///</summary>
		[ImplementPropertyType("sysOgTitle")]
		public string SysOgTitle
		{
			get { return this.GetPropertyValue<string>("sysOgTitle"); }
		}

		///<summary>
		/// Page Title
		///</summary>
		[ImplementPropertyType("sysPageTitle")]
		public string SysPageTitle
		{
			get { return this.GetPropertyValue<string>("sysPageTitle"); }
		}
	}

	/// <summary>Settings</summary>
	[PublishedContentModel("settings")]
	public partial class Settings : NestedContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "settings";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Settings(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Settings, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hide In Landing Page
		///</summary>
		[ImplementPropertyType("hideInContent")]
		public bool HideInContent
		{
			get { return this.GetPropertyValue<bool>("hideInContent"); }
		}

		///<summary>
		/// Hide in Sitemap: Don't add this page into the Sitemap
		///</summary>
		[ImplementPropertyType("hideInSitemap")]
		public bool HideInSitemap
		{
			get { return this.GetPropertyValue<bool>("hideInSitemap"); }
		}

		///<summary>
		/// URL Redirection
		///</summary>
		[ImplementPropertyType("overrideUrl")]
		public IEnumerable<IPublishedContent> OverrideUrl
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("overrideUrl"); }
		}

		///<summary>
		/// Hide in Top Navigation: If checked the page will not be shown.
		///</summary>
		[ImplementPropertyType("sysNavHide")]
		public bool SysNavHide
		{
			get { return this.GetPropertyValue<bool>("sysNavHide"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("sysNavTitle")]
		public string SysNavTitle
		{
			get { return this.GetPropertyValue<string>("sysNavTitle"); }
		}
	}

	/// <summary>Settings - Content Page</summary>
	[PublishedContentModel("settingsContentPage")]
	public partial class SettingsContentPage : NestedContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "settingsContentPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SettingsContentPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SettingsContentPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hide this page in Side Navigation: If checked the page will not be shown.
		///</summary>
		[ImplementPropertyType("hideInSubnavigation")]
		public bool HideInSubnavigation
		{
			get { return this.GetPropertyValue<bool>("hideInSubnavigation"); }
		}

		///<summary>
		/// Hide Side Navigation: If checked the side navigation menu will not be shown.
		///</summary>
		[ImplementPropertyType("hideSideNavigation")]
		public bool HideSideNavigation
		{
			get { return this.GetPropertyValue<bool>("hideSideNavigation"); }
		}

		///<summary>
		/// Show Container Fluid: To use full width on content page we will use container-fluid css class or container css class if not checked
		///</summary>
		[ImplementPropertyType("showContainerFluid")]
		public bool ShowContainerFluid
		{
			get { return this.GetPropertyValue<bool>("showContainerFluid"); }
		}
	}

	/// <summary>Content - Home Page</summary>
	[PublishedContentModel("contentHomePage")]
	public partial class ContentHomePage : NestedContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contentHomePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContentHomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentHomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner Image: 1366px x 600px
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("bannerImage"); }
		}

		///<summary>
		/// Sub Title
		///</summary>
		[ImplementPropertyType("subTitle")]
		public string SubTitle
		{
			get { return this.GetPropertyValue<string>("subTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Home Page</summary>
	[PublishedContentModel("homePage")]
	public partial class HomePage : Metadata
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Email Address
		///</summary>
		[ImplementPropertyType("emailAddress")]
		public string EmailAddress
		{
			get { return this.GetPropertyValue<string>("emailAddress"); }
		}

		///<summary>
		/// Facebook Link
		///</summary>
		[ImplementPropertyType("facebookLink")]
		public string FacebookLink
		{
			get { return this.GetPropertyValue<string>("facebookLink"); }
		}

		///<summary>
		/// Footer
		///</summary>
		[ImplementPropertyType("footer")]
		public Our.Umbraco.Vorto.Models.VortoValue Footer
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue>("footer"); }
		}

		///<summary>
		/// Google Map
		///</summary>
		[ImplementPropertyType("googleMap")]
		public string GoogleMap
		{
			get { return this.GetPropertyValue<string>("googleMap"); }
		}

		///<summary>
		/// Header Bottom Links
		///</summary>
		[ImplementPropertyType("headerBottomLinks")]
		public Our.Umbraco.Vorto.Models.VortoValue HeaderBottomLinks
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue>("headerBottomLinks"); }
		}

		///<summary>
		/// Header Links: Links on the top right corner of the website
		///</summary>
		[ImplementPropertyType("headerLinks")]
		public Our.Umbraco.Vorto.Models.VortoValue HeaderLinks
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue>("headerLinks"); }
		}

		///<summary>
		/// Instagram Link
		///</summary>
		[ImplementPropertyType("instagramLink")]
		public string InstagramLink
		{
			get { return this.GetPropertyValue<string>("instagramLink"); }
		}

		///<summary>
		/// LinkedIn Link
		///</summary>
		[ImplementPropertyType("linkedInLink")]
		public string LinkedInLink
		{
			get { return this.GetPropertyValue<string>("linkedInLink"); }
		}

		///<summary>
		/// Logo
		///</summary>
		[ImplementPropertyType("logo")]
		public IPublishedContent Logo
		{
			get { return this.GetPropertyValue<IPublishedContent>("logo"); }
		}

		///<summary>
		/// Mobile Number
		///</summary>
		[ImplementPropertyType("mobileNumber")]
		public string MobileNumber
		{
			get { return this.GetPropertyValue<string>("mobileNumber"); }
		}

		///<summary>
		/// Navigation
		///</summary>
		[ImplementPropertyType("navigation")]
		public Our.Umbraco.Vorto.Models.VortoValue Navigation
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue>("navigation"); }
		}

		///<summary>
		/// Navigation Logo
		///</summary>
		[ImplementPropertyType("navigationLogo")]
		public IPublishedContent NavigationLogo
		{
			get { return this.GetPropertyValue<IPublishedContent>("navigationLogo"); }
		}

		///<summary>
		/// News Letter Page: Page where the user will be redirected when subscribing for the newsletter
		///</summary>
		[ImplementPropertyType("newsLetterPage")]
		public IPublishedContent NewsLetterPage
		{
			get { return this.GetPropertyValue<IPublishedContent>("newsLetterPage"); }
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("pageContent")]
		public Our.Umbraco.Vorto.Models.VortoValue PageContent
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue>("pageContent"); }
		}

		///<summary>
		/// Search Page: Page where the user will be redirected when using the search
		///</summary>
		[ImplementPropertyType("searchPage")]
		public IPublishedContent SearchPage
		{
			get { return this.GetPropertyValue<IPublishedContent>("searchPage"); }
		}

		///<summary>
		/// Telephone Number
		///</summary>
		[ImplementPropertyType("telephoneNumber")]
		public string TelephoneNumber
		{
			get { return this.GetPropertyValue<string>("telephoneNumber"); }
		}

		///<summary>
		/// Twitter Link
		///</summary>
		[ImplementPropertyType("twitterLink")]
		public string TwitterLink
		{
			get { return this.GetPropertyValue<string>("twitterLink"); }
		}

		///<summary>
		/// Youtube Link
		///</summary>
		[ImplementPropertyType("youtubeLink")]
		public string YoutubeLink
		{
			get { return this.GetPropertyValue<string>("youtubeLink"); }
		}
	}

	/// <summary>Content - Child Links</summary>
	[PublishedContentModel("contentChildLinks")]
	public partial class ContentChildLinks : NestedContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contentChildLinks";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContentChildLinks(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentChildLinks, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Child Links
		///</summary>
		[ImplementPropertyType("childLinks")]
		public IEnumerable<RJP.MultiUrlPicker.Models.Link> ChildLinks
		{
			get { return this.GetPropertyValue<IEnumerable<RJP.MultiUrlPicker.Models.Link>>("childLinks"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public RJP.MultiUrlPicker.Models.Link Link
		{
			get { return this.GetPropertyValue<RJP.MultiUrlPicker.Models.Link>("link"); }
		}
	}

	/// <summary>Content - Navigation Links</summary>
	[PublishedContentModel("contentNavigationLinks")]
	public partial class ContentNavigationLinks : NestedContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contentNavigationLinks";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContentNavigationLinks(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentNavigationLinks, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Child Links
		///</summary>
		[ImplementPropertyType("childLinks")]
		public IEnumerable<IPublishedContent> ChildLinks
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("childLinks"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public RJP.MultiUrlPicker.Models.Link Link
		{
			get { return this.GetPropertyValue<RJP.MultiUrlPicker.Models.Link>("link"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Content - Navigation Columns</summary>
	[PublishedContentModel("contentNavigationColumns")]
	public partial class ContentNavigationColumns : NestedContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contentNavigationColumns";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContentNavigationColumns(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentNavigationColumns, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Navigation Content
		///</summary>
		[ImplementPropertyType("navigationContent")]
		public IEnumerable<IPublishedContent> NavigationContent
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("navigationContent"); }
		}
	}

	/// <summary>Content - Icon Link</summary>
	[PublishedContentModel("contentIconLink")]
	public partial class ContentIconLink : NestedContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contentIconLink";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContentIconLink(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentIconLink, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Icon
		///</summary>
		[ImplementPropertyType("icon")]
		public IPublishedContent Icon
		{
			get { return this.GetPropertyValue<IPublishedContent>("icon"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public RJP.MultiUrlPicker.Models.Link Link
		{
			get { return this.GetPropertyValue<RJP.MultiUrlPicker.Models.Link>("link"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Content - Header Link</summary>
	[PublishedContentModel("contentHeaderLink")]
	public partial class ContentHeaderLink : NestedContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contentHeaderLink";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContentHeaderLink(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentHeaderLink, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Child Links
		///</summary>
		[ImplementPropertyType("childLinks")]
		public IEnumerable<IPublishedContent> ChildLinks
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("childLinks"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public IPublishedContent Link
		{
			get { return this.GetPropertyValue<IPublishedContent>("link"); }
		}
	}

	/// <summary>Content - Footer</summary>
	[PublishedContentModel("contentFooter")]
	public partial class ContentFooter : NestedContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contentFooter";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContentFooter(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentFooter, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Bottom Links
		///</summary>
		[ImplementPropertyType("bottomLinks")]
		public IEnumerable<RJP.MultiUrlPicker.Models.Link> BottomLinks
		{
			get { return this.GetPropertyValue<IEnumerable<RJP.MultiUrlPicker.Models.Link>>("bottomLinks"); }
		}

		///<summary>
		/// Copyright
		///</summary>
		[ImplementPropertyType("copyright")]
		public string Copyright
		{
			get { return this.GetPropertyValue<string>("copyright"); }
		}

		///<summary>
		/// Footer Links
		///</summary>
		[ImplementPropertyType("footerLinks")]
		public IEnumerable<RJP.MultiUrlPicker.Models.Link> FooterLinks
		{
			get { return this.GetPropertyValue<IEnumerable<RJP.MultiUrlPicker.Models.Link>>("footerLinks"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Alt Text
		///</summary>
		[ImplementPropertyType("altText")]
		public Our.Umbraco.Vorto.Models.VortoValue AltText
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue>("altText"); }
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
